### ISSUE TITLE
future of this project ?

### ISSUE THREAD

**Issue by chandu0101** [bh5-js/react-navigator#1]
Hey , 
           first of all thanks alot for porting react-navigator to web , current i have a simple router based on react-navigator for mobile module , i am planning to create similar for web based this project , is this project currently used in prod ? or have plans to develop in future  ?  please let me know 

Thank You
Chandra

**Comment by euforic** [comment]
@chandu0101 sorry for the delay on updates. Most the updates have been internal, but we plan to release updates very soon to keep things in line with the react-native version. PRs are always welcome too :-)

**Comment by chandu0101** [comment]
> Most the updates have been internal, but we plan to release updates very soon to keep things in line with the react-native version

wow cool , looking forward to new release :+1:
